// 單字庫 - 這裡的單字將被您提供的單字表替換
const wordBank = [
    { english: "a", chinese: "一(個)" },
    { english: "A.M.", chinese: "上午" },
    { english: "ability", chinese: "能力、才能" },
    { english: "able", chinese: "能夠的、有才能的" },
    { english: "about", chinese: "大約、關於" },
    { english: "above", chinese: "在…上面、超過、大於" },
    { english: "abroad", chinese: "在國外、到國外" },
    { english: "absent", chinese: "缺席的、不在場的" },
    { english: "accept", chinese: "收受、接受" },
    { english: "accident", chinese: "意外事故" },
    { english: "achieve", chinese: "達到、完成、實現" },
    { english: "across", chinese: "橫過、在對面" },
    { english: "act", chinese: "表演、行為" },
    { english: "action", chinese: "行動、行為、動作" },
    { english: "active", chinese: "活躍的、積極的" },
    { english: "activity", chinese: "活動" },
    { english: "actor", chinese: "演員" },
    { english: "actress", chinese: "女演員" },
    { english: "actually", chinese: "實際上、事實上" },
    { english: "add", chinese: "加上、增加" },
    { english: "address", chinese: "地址、網址" },
    { english: "admire", chinese: "欽佩、欣賞" },
    { english: "adopt", chinese: "領養、接受" },
    { english: "adult", chinese: "成年人" },
    { english: "advance", chinese: "前進、發展" },
    { english: "advantage", chinese: "優點、優勢" },
    { english: "adventure", chinese: "冒險、奇遇" },
    { english: "advertisement", chinese: "廣告" },
    { english: "advice", chinese: "建議、忠告" },
    { english: "affect", chinese: "影響" },
    { english: "afraid", chinese: "害怕的" },
    { english: "after", chinese: "在...之後" },
    { english: "afternoon", chinese: "下午" },
    { english: "again", chinese: "又、再一次" },
    { english: "against", chinese: "反對、與...相反" },
    { english: "age", chinese: "年齡" },
    { english: "ago", chinese: "在…以前" },
    { english: "agree", chinese: "同意、贊成" },
    { english: "ahead", chinese: "在前面、領先" },
    { english: "air", chinese: "空氣、空中" },
    { english: "baby", chinese: "嬰兒" },
    { english: "back", chinese: "背部、後面" },
    { english: "bad", chinese: "壞的、不好的" },
    { english: "bag", chinese: "袋子" },
    { english: "ball", chinese: "球" },
    { english: "banana", chinese: "香蕉" },
    { english: "bank", chinese: "銀行" },
    { english: "basket", chinese: "籃子" },
    { english: "basketball", chinese: "籃球" },
    { english: "bath", chinese: "洗澡" },
    { english: "beach", chinese: "海灘" },
    { english: "bear", chinese: "熊" },
    { english: "beautiful", chinese: "美麗的" },
    { english: "bed", chinese: "床" },
    { english: "beef", chinese: "牛肉" },
    { english: "beer", chinese: "啤酒" },
    { english: "begin", chinese: "開始" },
    { english: "bell", chinese: "鈴、鐘" },
    { english: "below", chinese: "在...下面" },
    { english: "bird", chinese: "鳥" },
    { english: "birthday", chinese: "生日" },
    { english: "black", chinese: "黑色的" },
    { english: "blue", chinese: "藍色的" },
    { english: "boat", chinese: "船" },
    { english: "book", chinese: "書" },
    { english: "box", chinese: "箱子" },
    { english: "boy", chinese: "男孩" },
    { english: "bread", chinese: "麵包" },
    { english: "breakfast", chinese: "早餐" },
    { english: "bridge", chinese: "橋" },
    { english: "brother", chinese: "兄弟" },
    { english: "brown", chinese: "棕色的" },
    { english: "bus", chinese: "公車" },
    { english: "busy", chinese: "忙碌的" },
    { english: "butter", chinese: "奶油" },
    { english: "cake", chinese: "蛋糕" },
    { english: "call", chinese: "打電話" },
    { english: "camera", chinese: "相機" },
    { english: "car", chinese: "汽車" },
    { english: "card", chinese: "卡片" },
    { english: "cat", chinese: "貓" },
    { english: "chair", chinese: "椅子" },
    { english: "chicken", chinese: "雞肉" },
    { english: "child", chinese: "小孩" },
    { english: "chocolate", chinese: "巧克力" },
    { english: "church", chinese: "教堂" },
    { english: "city", chinese: "城市" },
    { english: "class", chinese: "班級" },
    { english: "clean", chinese: "乾淨的" },
    { english: "clock", chinese: "時鐘" },
    { english: "close", chinese: "關閉" },
    { english: "coffee", chinese: "咖啡" },
    { english: "cold", chinese: "冷的" },
    { english: "color", chinese: "顏色" },
    { english: "come", chinese: "來" },
    { english: "computer", chinese: "電腦" },
    { english: "cook", chinese: "煮" },
    { english: "cool", chinese: "涼爽的" },
    { english: "correct", chinese: "正確的" },
    { english: "cost", chinese: "成本" },
    { english: "count", chinese: "數" },
    { english: "country", chinese: "國家" },
    { english: "cow", chinese: "牛" },
    { english: "cry", chinese: "哭" },
    { english: "cup", chinese: "杯子" },
    { english: "cut", chinese: "切" },
    { english: "dance", chinese: "跳舞" },
    { english: "dark", chinese: "黑暗的" },
    { english: "date", chinese: "日期" },
    { english: "daughter", chinese: "女兒" },
    { english: "day", chinese: "天" },
    { english: "dead", chinese: "死的" },
    { english: "deep", chinese: "深的" },
    { english: "deer", chinese: "鹿" },
    { english: "desk", chinese: "書桌" },
    { english: "die", chinese: "死" },
    { english: "dinner", chinese: "晚餐" },
    { english: "dirty", chinese: "髒的" },
    { english: "dish", chinese: "盤子" },
    { english: "do", chinese: "做" },
    { english: "doctor", chinese: "醫生" },
    { english: "dog", chinese: "狗" },
    { english: "door", chinese: "門" },
    { english: "down", chinese: "向下" },
    { english: "draw", chinese: "畫" },
    { english: "dream", chinese: "夢" },
    { english: "dress", chinese: "洋裝" },
    { english: "drink", chinese: "喝" },
    { english: "drive", chinese: "開車" },
    { english: "drop", chinese: "掉下" },
    { english: "dry", chinese: "乾的" },
    { english: "duck", chinese: "鴨子" },
    { english: "ear", chinese: "耳朵" },
    { english: "early", chinese: "早的" },
    { english: "earth", chinese: "地球" },
    { english: "east", chinese: "東方" },
    { english: "easy", chinese: "容易的" },
    { english: "eat", chinese: "吃" },
    { english: "egg", chinese: "蛋" },
    { english: "eight", chinese: "八" },
    { english: "elephant", chinese: "大象" },
    { english: "end", chinese: "結束" },
    { english: "enemy", chinese: "敵人" },
    { english: "enjoy", chinese: "享受" },
    { english: "enough", chinese: "足夠的" },
    { english: "enter", chinese: "進入" },
    { english: "evening", chinese: "傍晚" },
    { english: "ever", chinese: "曾經" },
    { english: "every", chinese: "每個" },
    { english: "eye", chinese: "眼睛" },
    { english: "face", chinese: "臉" },
    { english: "fall", chinese: "跌倒" },
    { english: "family", chinese: "家庭" },
    { english: "far", chinese: "遠的" },
    { english: "farm", chinese: "農場" },
    { english: "fast", chinese: "快的" },
    { english: "father", chinese: "父親" },
    { english: "fear", chinese: "害怕" },
    { english: "feed", chinese: "餵食" },
    { english: "feel", chinese: "感覺" },
    { english: "few", chinese: "少的" },
    { english: "field", chinese: "田地" },
    { english: "fight", chinese: "打架" },
    { english: "find", chinese: "找到" },
    { english: "fine", chinese: "好的" },
    { english: "finger", chinese: "手指" },
    { english: "fire", chinese: "火" },
    { english: "first", chinese: "第一" },
    { english: "fish", chinese: "魚" },
    { english: "five", chinese: "五" },
    { english: "flag", chinese: "旗子" },
    { english: "flower", chinese: "花" },
    { english: "fly", chinese: "飛" },
    { english: "food", chinese: "食物" },
    { english: "foot", chinese: "腳" },
    { english: "for", chinese: "為了" },
    { english: "forest", chinese: "森林" },
    { english: "forget", chinese: "忘記" },
    { english: "fork", chinese: "叉子" },
    { english: "four", chinese: "四" },
    { english: "free", chinese: "免費的" },
    { english: "friend", chinese: "朋友" },
    { english: "frog", chinese: "青蛙" },
    { english: "fruit", chinese: "水果" },
    { english: "full", chinese: "滿的" },
    { english: "fun", chinese: "有趣的" },
    { english: "funny", chinese: "好笑的" },
    { english: "game", chinese: "遊戲" },
    { english: "garden", chinese: "花園" },
    { english: "gas", chinese: "汽油" },
    { english: "gate", chinese: "大門" },
    { english: "get", chinese: "得到" },
    { english: "gift", chinese: "禮物" },
    { english: "girl", chinese: "女孩" },
    { english: "give", chinese: "給" },
    { english: "glad", chinese: "高興的" },
    { english: "glass", chinese: "玻璃" },
    { english: "go", chinese: "去" },
    { english: "goat", chinese: "山羊" },
    { english: "god", chinese: "神" },
    { english: "gold", chinese: "金子" },
    { english: "good", chinese: "好的" },
    { english: "grass", chinese: "草" },
    { english: "gray", chinese: "灰色的" },
    { english: "great", chinese: "偉大的" },
    { english: "green", chinese: "綠色的" },
    { english: "ground", chinese: "地面" },
    { english: "group", chinese: "群體" },
    { english: "grow", chinese: "成長" },
    { english: "gun", chinese: "槍" },
    { english: "hair", chinese: "頭髮" },
    { english: "half", chinese: "一半" },
    { english: "hand", chinese: "手" },
    { english: "happy", chinese: "快樂的" },
    { english: "hard", chinese: "困難的" },
    { english: "hat", chinese: "帽子" },
    { english: "hate", chinese: "討厭" },
    { english: "have", chinese: "有" },
    { english: "he", chinese: "他" },
    { english: "head", chinese: "頭" },
    { english: "hear", chinese: "聽見" },
    { english: "heart", chinese: "心臟" },
    { english: "heat", chinese: "熱" },
    { english: "heavy", chinese: "重的" },
    { english: "hello", chinese: "哈囉" },
    { english: "help", chinese: "幫助" },
    { english: "hen", chinese: "母雞" },
    { english: "her", chinese: "她的" },
    { english: "here", chinese: "這裡" },
    { english: "hide", chinese: "躲藏" },
    { english: "high", chinese: "高的" },
    { english: "hill", chinese: "山丘" },
    { english: "him", chinese: "他" },
    { english: "his", chinese: "他的" },
    { english: "hit", chinese: "打" },
    { english: "hold", chinese: "握住" },
    { english: "hole", chinese: "洞" },
    { english: "home", chinese: "家" },
    { english: "hope", chinese: "希望" },
    { english: "horse", chinese: "馬" },
    { english: "hot", chinese: "熱的" },
    { english: "hotel", chinese: "飯店" },
    { english: "hour", chinese: "小時" },
    { english: "house", chinese: "房子" },
    { english: "how", chinese: "如何" },
    { english: "hundred", chinese: "百" },
    { english: "hungry", chinese: "餓的" },
    { english: "hunt", chinese: "打獵" },
    { english: "hurry", chinese: "趕快" },
    { english: "hurt", chinese: "受傷" },
    { english: "I", chinese: "我" },
    { english: "ice", chinese: "冰" },
    { english: "idea", chinese: "主意" },
    { english: "if", chinese: "如果" },
    { english: "ill", chinese: "生病的" },
    { english: "in", chinese: "在...裡" },
    { english: "into", chinese: "進入" },
    { english: "iron", chinese: "鐵" },
    { english: "is", chinese: "是" },
    { english: "it", chinese: "它" },
    { english: "its", chinese: "它的" },
    { english: "jar", chinese: "罐子" },
    { english: "job", chinese: "工作" },
    { english: "join", chinese: "加入" },
    { english: "juice", chinese: "果汁" },
    { english: "jump", chinese: "跳" },
    { english: "just", chinese: "剛剛" },
    { english: "keep", chinese: "保持" },
    { english: "key", chinese: "鑰匙" },
    { english: "kill", chinese: "殺" },
    { english: "kind", chinese: "種類" },
    { english: "king", chinese: "國王" },
    { english: "kitchen", chinese: "廚房" },
    { english: "knee", chinese: "膝蓋" },
    { english: "knife", chinese: "刀子" },
    { english: "know", chinese: "知道" },
    { english: "lady", chinese: "女士" },
    { english: "lake", chinese: "湖" },
    { english: "lamp", chinese: "燈" },
    { english: "land", chinese: "陸地" },
    { english: "large", chinese: "大的" },
    { english: "last", chinese: "最後的" },
    { english: "late", chinese: "晚的" },
    { english: "laugh", chinese: "笑" },
    { english: "lazy", chinese: "懶惰的" },
    { english: "lead", chinese: "領導" },
    { english: "leaf", chinese: "葉子" },
    { english: "learn", chinese: "學習" },
    { english: "leave", chinese: "離開" },
    { english: "leg", chinese: "腿" },
    { english: "left", chinese: "左邊" },
    { english: "lend", chinese: "借出" },
    { english: "length", chinese: "長度" },
    { english: "less", chinese: "較少的" },
    { english: "let", chinese: "讓" },
    { english: "letter", chinese: "信" },
    { english: "library", chinese: "圖書館" },
    { english: "lie", chinese: "說謊" },
    { english: "life", chinese: "生命" },
    { english: "lift", chinese: "舉起" },
    { english: "light", chinese: "光" },
    { english: "like", chinese: "喜歡" },
    { english: "line", chinese: "線" },
    { english: "lion", chinese: "獅子" },
    { english: "lip", chinese: "嘴唇" },
    { english: "list", chinese: "清單" },
    { english: "listen", chinese: "聽" },
    { english: "little", chinese: "小的" },
    { english: "live", chinese: "活著" },
    { english: "lock", chinese: "鎖" },
    { english: "lonely", chinese: "寂寞的" },
    { english: "long", chinese: "長的" },
    { english: "look", chinese: "看" },
    { english: "lose", chinese: "失去" },
    { english: "lot", chinese: "很多" },
    { english: "love", chinese: "愛" },
    { english: "low", chinese: "低的" },
    { english: "luck", chinese: "運氣" },
    { english: "lunch", chinese: "午餐" },
    { english: "machine", chinese: "機器" },
    { english: "mad", chinese: "生氣的" },
    { english: "magic", chinese: "魔法" },
    { english: "mail", chinese: "郵件" },
    { english: "main", chinese: "主要的" },
    { english: "make", chinese: "製作" },
    { english: "man", chinese: "男人" },
    { english: "many", chinese: "許多" },
    { english: "map", chinese: "地圖" },
    { english: "mark", chinese: "記號" },
    { english: "market", chinese: "市場" },
    { english: "marry", chinese: "結婚" },
    { english: "match", chinese: "火柴" },
    { english: "matter", chinese: "事情" },
    { english: "may", chinese: "可能" },
    { english: "meal", chinese: "餐點" },
    { english: "mean", chinese: "意思是" },
    { english: "meat", chinese: "肉" },
    { english: "medicine", chinese: "藥" },
    { english: "meet", chinese: "見面" },
    { english: "meeting", chinese: "會議" },
    { english: "member", chinese: "成員" },
    { english: "memory", chinese: "記憶" },
    { english: "men", chinese: "男人們" },
    { english: "metal", chinese: "金屬" },
    { english: "middle", chinese: "中間" },
    { english: "might", chinese: "可能" },
    { english: "mile", chinese: "英里" },
    { english: "milk", chinese: "牛奶" },
    { english: "mind", chinese: "心智" },
    { english: "mine", chinese: "我的" },
    { english: "minute", chinese: "分鐘" },
    { english: "miss", chinese: "想念" },
    { english: "mistake", chinese: "錯誤" },
    { english: "mix", chinese: "混合" },
    { english: "model", chinese: "模型" },
    { english: "modern", chinese: "現代的" },
    { english: "moment", chinese: "片刻" },
    { english: "money", chinese: "錢" },
    { english: "monkey", chinese: "猴子" },
    { english: "month", chinese: "月份" },
    { english: "moon", chinese: "月亮" },
    { english: "more", chinese: "更多" },
    { english: "morning", chinese: "早上" },
    { english: "most", chinese: "最多" },
    { english: "mother", chinese: "母親" },
    { english: "mountain", chinese: "山" },
    { english: "mouse", chinese: "老鼠" },
    { english: "mouth", chinese: "嘴巴" },
    { english: "move", chinese: "移動" },
    { english: "movie", chinese: "電影" },
    { english: "music", chinese: "音樂" },
    { english: "name", chinese: "名字" },
    { english: "narrow", chinese: "狹窄的" },
    { english: "nation", chinese: "國家" },
    { english: "nature", chinese: "自然" },
    { english: "near", chinese: "靠近" },
    { english: "neck", chinese: "脖子" },
    { english: "need", chinese: "需要" },
    { english: "needle", chinese: "針" },
    { english: "neighbor", chinese: "鄰居" },
    { english: "neither", chinese: "兩者都不" },
    { english: "nest", chinese: "巢" },
    { english: "net", chinese: "網" },
    { english: "never", chinese: "從不" },
    { english: "new", chinese: "新的" },
    { english: "news", chinese: "新聞" },
    { english: "newspaper", chinese: "報紙" },
    { english: "next", chinese: "下一個" },
    { english: "nice", chinese: "好的" },
    { english: "night", chinese: "夜晚" },
    { english: "nine", chinese: "九" },
    { english: "no", chinese: "不" },
    { english: "noise", chinese: "噪音" },
    { english: "none", chinese: "沒有一個" },
    { english: "noon", chinese: "中午" },
    { english: "north", chinese: "北方" },
    { english: "nose", chinese: "鼻子" },
    { english: "not", chinese: "不是" },
    { english: "note", chinese: "筆記" },
    { english: "nothing", chinese: "沒有東西" },
    { english: "notice", chinese: "注意" },
    { english: "now", chinese: "現在" },
    { english: "number", chinese: "數字" },
    { english: "nurse", chinese: "護士" },
    { english: "ocean", chinese: "海洋" },
    { english: "of", chinese: "的" },
    { english: "off", chinese: "離開" },
    { english: "offer", chinese: "提供" },
    { english: "office", chinese: "辦公室" },
    { english: "often", chinese: "經常" },
    { english: "oil", chinese: "油" },
    { english: "old", chinese: "老的" },
    { english: "on", chinese: "在...上" },
    { english: "once", chinese: "一次" },
    { english: "one", chinese: "一" },
    { english: "only", chinese: "只有" },
    { english: "open", chinese: "打開" },
    { english: "opposite", chinese: "相反的" },
    { english: "or", chinese: "或者" },
    { english: "orange", chinese: "橘子" },
    { english: "order", chinese: "命令" },
    { english: "other", chinese: "其他的" },
    { english: "our", chinese: "我們的" },
    { english: "out", chinese: "出去" },
    { english: "outside", chinese: "外面" },
    { english: "over", chinese: "結束" },
    { english: "own", chinese: "擁有" },
    { english: "page", chinese: "頁" },
    { english: "pain", chinese: "疼痛" },
    { english: "paint", chinese: "油漆" },
    { english: "pair", chinese: "一對" },
    { english: "pan", chinese: "平底鍋" },
    { english: "paper", chinese: "紙" },
    { english: "parent", chinese: "父母" },
    { english: "park", chinese: "公園" },
    { english: "part", chinese: "部分" },
    { english: "party", chinese: "派對" },
    { english: "pass", chinese: "通過" },
    { english: "past", chinese: "過去" },
    { english: "path", chinese: "小路" },
    { english: "pay", chinese: "支付" },
    { english: "peace", chinese: "和平" },
    { english: "pen", chinese: "筆" },
    { english: "pencil", chinese: "鉛筆" },
    { english: "people", chinese: "人們" },
    { english: "perfect", chinese: "完美的" },
    { english: "perhaps", chinese: "也許" },
    { english: "person", chinese: "人" },
    { english: "pet", chinese: "寵物" },
    { english: "phone", chinese: "電話" },
    { english: "pick", chinese: "挑選" },
    { english: "picture", chinese: "圖片" },
    { english: "pie", chinese: "派" },
    { english: "piece", chinese: "片" },
    { english: "pig", chinese: "豬" },
    { english: "pile", chinese: "堆" },
    { english: "pin", chinese: "別針" },
    { english: "pink", chinese: "粉紅色" },
    { english: "pipe", chinese: "管子" },
    { english: "place", chinese: "地方" },
    { english: "plan", chinese: "計劃" },
    { english: "plane", chinese: "飛機" },
    { english: "plant", chinese: "植物" },
    { english: "plate", chinese: "盤子" },
    { english: "play", chinese: "玩" },
    { english: "please", chinese: "請" },
    { english: "plenty", chinese: "充足" },
    { english: "pocket", chinese: "口袋" },
    { english: "point", chinese: "指向" },
    { english: "poison", chinese: "毒藥" },
    { english: "police", chinese: "警察" },
    { english: "pool", chinese: "游泳池" },
    { english: "poor", chinese: "貧窮的" },
    { english: "popular", chinese: "受歡迎的" },
    { english: "porch", chinese: "門廊" },
    { english: "port", chinese: "港口" },
    { english: "position", chinese: "位置" },
    { english: "possible", chinese: "可能的" },
    { english: "post", chinese: "郵寄" },
    { english: "pot", chinese: "鍋" },
    { english: "pound", chinese: "磅" },
    { english: "pour", chinese: "倒" },
    { english: "powder", chinese: "粉" },
    { english: "power", chinese: "力量" },
    { english: "practice", chinese: "練習" },
    { english: "prepare", chinese: "準備" },
    { english: "present", chinese: "禮物" },
    { english: "press", chinese: "按" },
    { english: "pretty", chinese: "漂亮的" },
    { english: "price", chinese: "價格" },
    { english: "print", chinese: "印刷" },
    { english: "prison", chinese: "監獄" },
    { english: "private", chinese: "私人的" },
    { english: "prize", chinese: "獎品" },
    { english: "probably", chinese: "可能" },
    { english: "problem", chinese: "問題" },
    { english: "produce", chinese: "生產" },
    { english: "promise", chinese: "承諾" },
    { english: "proper", chinese: "適當的" },
    { english: "protect", chinese: "保護" },
    { english: "proud", chinese: "驕傲的" },
    { english: "public", chinese: "公共的" },
    { english: "pull", chinese: "拉" },
    { english: "push", chinese: "推" },
    { english: "put", chinese: "放" },
    { english: "queen", chinese: "女王" },
    { english: "question", chinese: "問題" },
    { english: "quick", chinese: "快的" },
    { english: "quiet", chinese: "安靜的" },
    { english: "quite", chinese: "相當" },
    { english: "rabbit", chinese: "兔子" },
    { english: "race", chinese: "比賽" },
    { english: "radio", chinese: "收音機" },
    { english: "rail", chinese: "鐵軌" },
    { english: "rain", chinese: "雨" },
    { english: "raise", chinese: "舉起" },
    { english: "range", chinese: "範圍" },
    { english: "rank", chinese: "等級" },
    { english: "rat", chinese: "老鼠" },
    { english: "rather", chinese: "寧可" },
    { english: "raw", chinese: "生的" },
    { english: "reach", chinese: "到達" },
    { english: "read", chinese: "閱讀" },
    { english: "ready", chinese: "準備好的" },
    { english: "real", chinese: "真實的" },
    { english: "reason", chinese: "理由" },
    { english: "receive", chinese: "收到" },
    { english: "record", chinese: "記錄" },
    { english: "red", chinese: "紅色" },
    { english: "remember", chinese: "記得" },
    { english: "remind", chinese: "提醒" },
    { english: "remove", chinese: "移除" },
    { english: "rent", chinese: "租" },
    { english: "repair", chinese: "修理" },
    { english: "repeat", chinese: "重複" },
    { english: "reply", chinese: "回答" },
    { english: "report", chinese: "報告" },
    { english: "rest", chinese: "休息" },
    { english: "result", chinese: "結果" },
    { english: "return", chinese: "返回" },
    { english: "rice", chinese: "米" },
    { english: "rich", chinese: "富有的" },
    { english: "ride", chinese: "騎" },
    { english: "right", chinese: "右邊" },
    { english: "ring", chinese: "戒指" },
    { english: "rise", chinese: "上升" },
    { english: "river", chinese: "河" },
    { english: "road", chinese: "路" },
    { english: "rock", chinese: "岩石" },
    { english: "roll", chinese: "滾動" },
    { english: "roof", chinese: "屋頂" },
    { english: "room", chinese: "房間" },
    { english: "root", chinese: "根" },
    { english: "rope", chinese: "繩子" },
    { english: "rose", chinese: "玫瑰" },
    { english: "round", chinese: "圓的" },
    { english: "row", chinese: "排" },
    { english: "rub", chinese: "摩擦" },
    { english: "rubber", chinese: "橡膠" },
    { english: "rule", chinese: "規則" },
    { english: "run", chinese: "跑" },
    { english: "rush", chinese: "匆忙" },
    { english: "sad", chinese: "傷心的" },
    { english: "safe", chinese: "安全的" },
    { english: "sail", chinese: "航行" },
    { english: "salt", chinese: "鹽" },
    { english: "same", chinese: "相同的" },
    { english: "sand", chinese: "沙" },
    { english: "save", chinese: "儲存" },
    { english: "say", chinese: "說" },
    { english: "school", chinese: "學校" },
    { english: "science", chinese: "科學" },
    { english: "scissors", chinese: "剪刀" },
    { english: "score", chinese: "分數" },
    { english: "screen", chinese: "螢幕" },
    { english: "sea", chinese: "海" },
    { english: "search", chinese: "搜尋" },
    { english: "season", chinese: "季節" },
    { english: "seat", chinese: "座位" },
    { english: "second", chinese: "第二" },
    { english: "secret", chinese: "秘密" },
    { english: "see", chinese: "看見" },
    { english: "seed", chinese: "種子" },
    { english: "seem", chinese: "似乎" },
    { english: "self", chinese: "自己" },
    { english: "sell", chinese: "賣" },
    { english: "send", chinese: "寄送" },
    { english: "sense", chinese: "感覺" },
    { english: "sentence", chinese: "句子" },
    { english: "separate", chinese: "分開" },
    { english: "serious", chinese: "嚴肅的" },
    { english: "serve", chinese: "服務" },
    { english: "set", chinese: "設置" },
    { english: "seven", chinese: "七" },
    { english: "several", chinese: "幾個" },
    { english: "shade", chinese: "陰影" },
    { english: "shadow", chinese: "影子" },
    { english: "shake", chinese: "搖" },
    { english: "shall", chinese: "將要" },
    { english: "shape", chinese: "形狀" },
    { english: "share", chinese: "分享" },
    { english: "sharp", chinese: "尖銳的" },
    { english: "sheep", chinese: "綿羊" },
    { english: "sheet", chinese: "床單" },
    { english: "shelf", chinese: "架子" },
    { english: "shell", chinese: "殼" },
    { english: "shine", chinese: "發光" },
    { english: "ship", chinese: "船" },
    { english: "shirt", chinese: "襯衫" },
    { english: "shoe", chinese: "鞋子" },
    { english: "shoot", chinese: "射擊" },
    { english: "shop", chinese: "商店" },
    { english: "short", chinese: "短的" },
    { english: "should", chinese: "應該" },
    { english: "shoulder", chinese: "肩膀" },
    { english: "shout", chinese: "喊叫" },
    { english: "show", chinese: "展示" },
    { english: "sick", chinese: "生病的" },
    { english: "side", chinese: "側邊" },
    { english: "sign", chinese: "標誌" },
    { english: "silver", chinese: "銀" },
    { english: "simple", chinese: "簡單的" },
    { english: "sing", chinese: "唱歌" },
    { english: "sink", chinese: "水槽" },
    { english: "sister", chinese: "姊妹" },
    { english: "sit", chinese: "坐" },
    { english: "six", chinese: "六" },
    { english: "size", chinese: "尺寸" },
    { english: "skill", chinese: "技能" },
    { english: "skin", chinese: "皮膚" },
    { english: "skirt", chinese: "裙子" },
    { english: "sky", chinese: "天空" },
    { english: "slave", chinese: "奴隸" },
    { english: "sleep", chinese: "睡覺" },
    { english: "slip", chinese: "滑倒" },
    { english: "slow", chinese: "慢的" },
    { english: "small", chinese: "小的" },
    { english: "smell", chinese: "聞" },
    { english: "smile", chinese: "微笑" },
    { english: "smoke", chinese: "煙" },
    { english: "snow", chinese: "雪" },
    { english: "so", chinese: "所以" },
    { english: "soap", chinese: "肥皂" },
    { english: "sock", chinese: "襪子" },
    { english: "soft", chinese: "軟的" },
    { english: "soil", chinese: "土壤" },
    { english: "soldier", chinese: "士兵" },
    { english: "some", chinese: "一些" },
    { english: "son", chinese: "兒子" },
    { english: "soon", chinese: "很快" },
    { english: "sorry", chinese: "抱歉" },
    { english: "sort", chinese: "分類" },
    { english: "soul", chinese: "靈魂" },
    { english: "sound", chinese: "聲音" },
    { english: "soup", chinese: "湯" },
    { english: "south", chinese: "南方" },
    { english: "space", chinese: "空間" },
    { english: "speak", chinese: "說話" },
    { english: "special", chinese: "特別的" },
    { english: "speed", chinese: "速度" },
    { english: "spell", chinese: "拼寫" },
    { english: "spend", chinese: "花費" },
    { english: "spoon", chinese: "湯匙" },
    { english: "sport", chinese: "運動" },
    { english: "spread", chinese: "傳播" },
    { english: "spring", chinese: "春天" },
    { english: "square", chinese: "正方形" },
    { english: "stage", chinese: "舞台" },
    { english: "stairs", chinese: "樓梯" },
    { english: "stamp", chinese: "郵票" },
    { english: "stand", chinese: "站立" },
    { english: "star", chinese: "星星" },
    { english: "start", chinese: "開始" },
    { english: "state", chinese: "狀態" },
    { english: "station", chinese: "車站" },
    { english: "stay", chinese: "停留" },
    { english: "steal", chinese: "偷" },
    { english: "steam", chinese: "蒸氣" },
    { english: "steel", chinese: "鋼" },
    { english: "step", chinese: "步驟" },
    { english: "stick", chinese: "棍子" },
    { english: "still", chinese: "仍然" },
    { english: "stone", chinese: "石頭" },
    { english: "stop", chinese: "停止" },
    { english: "store", chinese: "商店" },
    { english: "storm", chinese: "暴風雨" },
    { english: "story", chinese: "故事" },
    { english: "strange", chinese: "奇怪的" },
    { english: "street", chinese: "街道" },
    { english: "stretch", chinese: "伸展" },
    { english: "strike", chinese: "打擊" },
    { english: "strong", chinese: "強壯的" },
    { english: "student", chinese: "學生" },
    { english: "study", chinese: "學習" },
    { english: "stupid", chinese: "愚蠢的" },
    { english: "subject", chinese: "主題" },
    { english: "substance", chinese: "物質" },
    { english: "success", chinese: "成功" },
    { english: "such", chinese: "如此" },
    { english: "sudden", chinese: "突然的" },
    { english: "sugar", chinese: "糖" },
    { english: "summer", chinese: "夏天" },
    { english: "sun", chinese: "太陽" },
    { english: "supply", chinese: "供應" },
    { english: "support", chinese: "支持" },
    { english: "sure", chinese: "確定的" },
    { english: "surface", chinese: "表面" },
    { english: "surprise", chinese: "驚喜" },
    { english: "sweet", chinese: "甜的" },
    { english: "swim", chinese: "游泳" },
    { english: "table", chinese: "桌子" },
    { english: "tail", chinese: "尾巴" },
    { english: "take", chinese: "拿" },
    { english: "talk", chinese: "談話" },
    { english: "tall", chinese: "高的" },
    { english: "taste", chinese: "味道" },
    { english: "tax", chinese: "稅" },
    { english: "tea", chinese: "茶" },
    { english: "teach", chinese: "教" },
    { english: "team", chinese: "團隊" },
    { english: "tear", chinese: "眼淚" },
    { english: "telephone", chinese: "電話" },
    { english: "tell", chinese: "告訴" },
    { english: "ten", chinese: "十" },
    { english: "test", chinese: "測驗" },
    { english: "than", chinese: "比" },
    { english: "that", chinese: "那個" },
    { english: "the", chinese: "這個" },
    { english: "their", chinese: "他們的" },
    { english: "then", chinese: "然後" },
    { english: "there", chinese: "那裡" },
    { english: "these", chinese: "這些" },
    { english: "they", chinese: "他們" },
    { english: "thick", chinese: "厚的" },
    { english: "thin", chinese: "薄的" },
    { english: "thing", chinese: "東西" },
    { english: "think", chinese: "思考" },
    { english: "third", chinese: "第三" },
    { english: "this", chinese: "這個" },
    { english: "though", chinese: "雖然" },
    { english: "thought", chinese: "想法" },
    { english: "thousand", chinese: "千" },
    { english: "thread", chinese: "線" },
    { english: "three", chinese: "三" },
    { english: "throat", chinese: "喉嚨" },
    { english: "through", chinese: "穿過" },
    { english: "thumb", chinese: "拇指" },
    { english: "thunder", chinese: "雷" },
    { english: "ticket", chinese: "票" },
    { english: "tie", chinese: "領帶" },
    { english: "tight", chinese: "緊的" },
    { english: "till", chinese: "直到" },
    { english: "time", chinese: "時間" },
    { english: "tire", chinese: "輪胎" },
    { english: "tired", chinese: "疲倦的" },
    { english: "title", chinese: "標題" },
    { english: "to", chinese: "到" },
    { english: "toe", chinese: "腳趾" },
    { english: "together", chinese: "一起" },
    { english: "tomorrow", chinese: "明天" },
    { english: "tongue", chinese: "舌頭" },
    { english: "tonight", chinese: "今晚" },
    { english: "too", chinese: "也" },
    { english: "tooth", chinese: "牙齒" },
    { english: "top", chinese: "頂部" },
    { english: "touch", chinese: "觸摸" },
    { english: "town", chinese: "城鎮" },
    { english: "trade", chinese: "貿易" },
    { english: "train", chinese: "火車" },
    { english: "tram", chinese: "電車" },
    { english: "travel", chinese: "旅行" },
    { english: "tree", chinese: "樹" },
    { english: "trick", chinese: "把戲" },
    { english: "trip", chinese: "旅程" },
    { english: "trouble", chinese: "麻煩" },
    { english: "true", chinese: "真實的" },
    { english: "trust", chinese: "信任" },
    { english: "try", chinese: "嘗試" },
    { english: "tube", chinese: "管子" },
    { english: "turn", chinese: "轉" },
    { english: "twice", chinese: "兩次" },
    { english: "two", chinese: "二" },
    { english: "type", chinese: "類型" },
    { english: "ugly", chinese: "醜的" },
    { english: "umbrella", chinese: "雨傘" },
    { english: "uncle", chinese: "叔叔" },
    { english: "under", chinese: "在...下" },
    { english: "understand", chinese: "理解" },
    { english: "unit", chinese: "單位" },
    { english: "until", chinese: "直到" },
    { english: "up", chinese: "向上" },
    { english: "use", chinese: "使用" },
    { english: "useful", chinese: "有用的" },
    { english: "usual", chinese: "通常的" },
    { english: "valley", chinese: "山谷" },
    { english: "value", chinese: "價值" },
    { english: "vegetable", chinese: "蔬菜" },
    { english: "very", chinese: "非常" },
    { english: "vessel", chinese: "容器" },
    { english: "victory", chinese: "勝利" },
    { english: "view", chinese: "景色" },
    { english: "village", chinese: "村莊" },
    { english: "violence", chinese: "暴力" },
    { english: "voice", chinese: "聲音" },
    { english: "visit", chinese: "拜訪" },
    { english: "wait", chinese: "等待" },
    { english: "wake", chinese: "醒來" },
    { english: "walk", chinese: "走路" },
    { english: "wall", chinese: "牆" },
    { english: "want", chinese: "想要" },
    { english: "war", chinese: "戰爭" },
    { english: "warm", chinese: "溫暖的" },
    { english: "wash", chinese: "洗" },
    { english: "waste", chinese: "浪費" },
    { english: "watch", chinese: "手錶" },
    { english: "water", chinese: "水" },
    { english: "wave", chinese: "波浪" },
    { english: "way", chinese: "方式" },
    { english: "we", chinese: "我們" },
    { english: "weak", chinese: "虛弱的" },
    { english: "wealth", chinese: "財富" },
    { english: "wear", chinese: "穿" },
    { english: "weather", chinese: "天氣" },
    { english: "week", chinese: "星期" },
    { english: "weigh", chinese: "重量" },
    { english: "welcome", chinese: "歡迎" },
    { english: "well", chinese: "好" },
    { english: "west", chinese: "西方" },
    { english: "wet", chinese: "濕的" },
    { english: "what", chinese: "什麼" },
    { english: "wheel", chinese: "輪子" },
    { english: "when", chinese: "何時" },
    { english: "where", chinese: "哪裡" },
    { english: "which", chinese: "哪個" },
    { english: "while", chinese: "當...的時候" },
    { english: "white", chinese: "白色的" },
    { english: "who", chinese: "誰" },
    { english: "whole", chinese: "整個" },
    { english: "why", chinese: "為什麼" },
    { english: "wide", chinese: "寬的" },
    { english: "wife", chinese: "妻子" },
    { english: "wild", chinese: "野生的" },
    { english: "will", chinese: "將要" },
    { english: "win", chinese: "贏" },
    { english: "wind", chinese: "風" },
    { english: "window", chinese: "窗戶" },
    { english: "wine", chinese: "葡萄酒" },
    { english: "wing", chinese: "翅膀" },
    { english: "winter", chinese: "冬天" },
    { english: "wire", chinese: "電線" },
    { english: "wise", chinese: "明智的" },
    { english: "with", chinese: "和" },
    { english: "woman", chinese: "女人" },
    { english: "wood", chinese: "木頭" },
    { english: "word", chinese: "單字" },
    { english: "work", chinese: "工作" },
    { english: "world", chinese: "世界" },
    { english: "wound", chinese: "傷口" },
    { english: "write", chinese: "寫" },
    { english: "wrong", chinese: "錯誤的" },
    { english: "year", chinese: "年" },
    { english: "yellow", chinese: "黃色的" },
    { english: "yes", chinese: "是的" },
    { english: "yesterday", chinese: "昨天" },
    { english: "yet", chinese: "還" },
    { english: "you", chinese: "你" },
    { english: "young", chinese: "年輕的" },
    { english: "zero", chinese: "零" },
    { english: "zoo", chinese: "動物園" }
];

let currentQuestions = [];
let currentQuestionIndex = 0;
let score = 0;
let timer;
let timeLeft;

const wordDisplay = document.getElementById('word-display');
const optionsContainer = document.getElementById('options-container');
const startButton = document.getElementById('start-btn');
const scoreDisplay = document.getElementById('score');
const resultMessage = document.getElementById('result-message');
const timeDisplay = document.getElementById('time');
const speakButton = document.getElementById('speak-btn');

function speakWord(word) {
    const utterance = new SpeechSynthesisUtterance(word);
    utterance.lang = 'en-US';
    utterance.rate = 0.8;
    speechSynthesis.speak(utterance);
}

speakButton.addEventListener('click', () => {
    const currentWord = currentQuestions[currentQuestionIndex];
    speakWord(currentWord.english);
});

function startTimer() {
    timeLeft--;
    timeDisplay.textContent = timeLeft;
    
    // 當時間少於5秒時，添加警示效果
    if (timeLeft <= 5) {
        timeDisplay.style.color = 'red';
        timeDisplay.style.fontWeight = 'bold';
    } else {
        timeDisplay.style.color = 'black';
        timeDisplay.style.fontWeight = 'normal';
    }

    if (timeLeft <= 0) {
        handleTimeUp();
    }
}

function handleTimeUp() {
    clearInterval(timer);
    const currentWord = currentQuestions[currentQuestionIndex];
    
    // 禁用所有按鈕
    const buttons = optionsContainer.getElementsByTagName('button');
    for (let button of buttons) {
        button.disabled = true;
        if (button.textContent === currentWord.chinese) {
            button.style.backgroundColor = '#4CAF50';  // 顯示正確答案
        }
    }

    resultMessage.textContent = '時間到！正確答案是：' + currentWord.chinese;
    
    setTimeout(() => {
        currentQuestionIndex++;
        resultMessage.textContent = '';
        timeDisplay.style.color = 'black';  // 重置顏色
        timeDisplay.style.fontWeight = 'normal';  // 重置字體粗細
        displayQuestion();
    }, 1500);
}

function displayQuestion() {
    if (currentQuestionIndex >= 20) {
        endQuiz();
        return;
    }

    const currentWord = currentQuestions[currentQuestionIndex];
    const options = generateOptions(currentWord.chinese);
    
    wordDisplay.textContent = currentWord.english;
    optionsContainer.innerHTML = '';
    
    options.forEach(option => {
        const button = document.createElement('button');
        button.textContent = option;
        button.onclick = () => checkAnswer(option, currentWord.chinese);
        optionsContainer.appendChild(button);
    });

    // 重置計時器和顯示效果
    clearInterval(timer);
    timeLeft = 15;
    timeDisplay.textContent = timeLeft;
    timeDisplay.style.color = 'black';
    timeDisplay.style.fontWeight = 'normal';
    timer = setInterval(startTimer, 1000);
}

function selectRandomQuestions() {
    const shuffled = [...wordBank].sort(() => 0.5 - Math.random());
    return shuffled.slice(0, 20);  // 改為選20題
}

function generateOptions(correctAnswer) {
    let options = [correctAnswer];
    const otherWords = wordBank.filter(word => word.chinese !== correctAnswer);
    const shuffled = otherWords.sort(() => 0.5 - Math.random());
    options = options.concat(shuffled.slice(0, 3).map(word => word.chinese));
    return options.sort(() => 0.5 - Math.random());
}

function checkAnswer(selected, correct) {
    clearInterval(timer);
    const buttons = optionsContainer.getElementsByTagName('button');
    
    for (let button of buttons) {
        button.disabled = true;
        if (button.textContent === correct) {
            button.style.backgroundColor = '#4CAF50';  // 顯示正確答案
        } else if (button.textContent === selected && selected !== correct) {
            button.style.backgroundColor = '#ff4444';  // 顯示錯誤選項
        }
    }

    if (selected === correct) {
        score += 5;
        scoreDisplay.textContent = score;
        resultMessage.textContent = '答對了！';
    } else {
        resultMessage.textContent = '答錯了！正確答案是：' + correct;
    }

    setTimeout(() => {
        currentQuestionIndex++;
        resultMessage.textContent = '';  // 清除結果訊息
        displayQuestion();
    }, 1500);
}

function nextQuestion() {
    currentQuestionIndex++;
    if (currentQuestionIndex < currentQuestions.length) {
        displayQuestion();
        resultMessage.textContent = '';
    } else {
        endQuiz();
    }
}

function endQuiz() {
    clearInterval(timer);
    wordDisplay.textContent = '測驗結束！';
    optionsContainer.innerHTML = '';
    resultMessage.textContent = `最終得分：${score}分`;
    startButton.style.display = 'block';
    timeDisplay.textContent = '0';
    speakButton.style.display = 'none';
}

function startQuiz() {
    score = 0;
    scoreDisplay.textContent = score;
    currentQuestionIndex = 0;
    currentQuestions = selectRandomQuestions();
    startButton.style.display = 'none';
    resultMessage.textContent = '';
    displayQuestion();
}

startButton.addEventListener('click', startQuiz);
